### ISSUE TITLE
Implement command logging

### ISSUE THREAD

**Issue by rytse** [blair-robot-project/449-central-repo#2]
`ReferencingCommand`s should log in every method call.

`initialize`/`end`/`interrupt` methods should all log the command name and the respective action (init, end, interrupt).

`execute` should log data provided in a method overrided in subclasses that need to log every execute cycle.

Users should be able to choose whether to send the logs to the console, a single log file, separate log files, nowhere, or a combination of the above.

This would greatly expedite debugging.

Note: Long term todo

**Comment by ryegleason** [comment]
We have Logger now.
